# Generated by Django 4.2 on 2023-05-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='followers_profile', to='Accounts.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='following_profiles', to='Accounts.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='Main.interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='researches',
            field=models.ManyToManyField(blank=True, to='Main.research'),
        ),
    ]
